start: ask1.o proc-common.o ask2.o ask3.o ask41.o tree.o
    gcc -o ask1 ask1.o proc-common.o
    gcc -o ask2 ask2.o proc-common.o tree.o
    gcc -o ask3 ask3.o proc-common.o tree.o
    gcc -o ask41 ask41.o proc-common.o tree.o

ask1.o: ask1.c
    gcc -c -Wall ask1.c

ask2.o: ask2.c
    gcc -c -Wall ask2.c

ask3.o: ask3.c
    gcc -c -Wall ask3.c

ask41.o: ask41.c
    gcc -c -Wall ask41.c

